// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: canteen.proto

package grpc.examples.canteen;

public final class CanteenServiceImpl {
  private CanteenServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MenuRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MenuRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MenuResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MenuResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReturnMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReturnMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcanteen.proto\"\r\n\013MenuRequest\"7\n\014MenuRe" +
      "sponse\022\014\n\004text\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005pric" +
      "e\030\003 \001(\002\">\n\014OrderRequest\022\020\n\010username\030\001 \001(" +
      "\t\022\020\n\010quantity\030\002 \001(\005\022\n\n\002id\030\003 \001(\005\" \n\rRetur" +
      "nMessage\022\017\n\007message\030\001 \001(\t\" \n\014OrderMessag" +
      "e\022\020\n\010username\030\001 \001(\t\"?\n\rOrderResponse\022\020\n\010" +
      "username\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\020\n\010quantity\030\003" +
      " \001(\0052\240\001\n\016CanteenService\022*\n\007getMenu\022\014.Men" +
      "uRequest\032\r.MenuResponse\"\0000\001\022/\n\norderItem" +
      "s\022\r.OrderRequest\032\016.ReturnMessage\"\000(\001\0221\n\n" +
      "viewOrders\022\r.OrderMessage\032\016.OrderRespons" +
      "e\"\000(\0010\001B-\n\025grpc.examples.canteenB\022Cantee" +
      "nServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MenuRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MenuRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MenuRequest_descriptor,
        new java.lang.String[] { });
    internal_static_MenuResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MenuResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MenuResponse_descriptor,
        new java.lang.String[] { "Text", "Id", "Price", });
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new java.lang.String[] { "Username", "Quantity", "Id", });
    internal_static_ReturnMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ReturnMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReturnMessage_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_OrderMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OrderMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderMessage_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderResponse_descriptor,
        new java.lang.String[] { "Username", "Id", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
