// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: canteen.proto

package grpc.examples.canteen;

public interface MenuResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MenuResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>float price = 3;</code>
   */
  float getPrice();
}
