// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: canteen.proto

package grpc.examples.canteen;

public interface MenuRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MenuRequest)
    com.google.protobuf.MessageOrBuilder {
}
