// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: canteen.proto

package grpc.examples.canteen;

public interface OrderMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
