// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.examples.printer;

public interface AvailabilityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AvailabilityRequest)
    com.google.protobuf.MessageOrBuilder {
}
