// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.examples.printer;

public interface AvailabilityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AvailabilityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string location = 2;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
