// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.examples.printer;

public interface PrintRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PrintRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();
}
