// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.examples.printer;

public final class PrinterServiceImpl {
  private PrinterServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AvailabilityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AvailabilityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AvailabilityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AvailabilityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrintRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrintRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrintResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PrintResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReturnMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReturnMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprinter.proto\"\025\n\023AvailabilityRequest\"4" +
      "\n\024AvailabilityResponse\022\n\n\002id\030\001 \001(\005\022\020\n\010lo" +
      "cation\030\002 \001(\t\" \n\014PrintRequest\022\020\n\010filename" +
      "\030\001 \001(\t\" \n\rPrintResponse\022\017\n\007message\030\001 \001(\t" +
      "\"\033\n\rStatusRequest\022\n\n\002id\030\001 \001(\005\" \n\rReturnM" +
      "essage\022\017\n\007message\030\001 \001(\t2\266\001\n\016PrinterServi" +
      "ce\022?\n\014listPrinters\022\024.AvailabilityRequest" +
      "\032\025.AvailabilityResponse\"\0000\001\0220\n\rprintDocu" +
      "ment\022\r.PrintRequest\032\016.PrintResponse\"\000\0221\n" +
      "\rprinterStatus\022\016.StatusRequest\032\016.ReturnM" +
      "essage\"\000B-\n\025grpc.examples.printerB\022Print" +
      "erServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AvailabilityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AvailabilityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AvailabilityRequest_descriptor,
        new java.lang.String[] { });
    internal_static_AvailabilityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AvailabilityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AvailabilityResponse_descriptor,
        new java.lang.String[] { "Id", "Location", });
    internal_static_PrintRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PrintRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrintRequest_descriptor,
        new java.lang.String[] { "Filename", });
    internal_static_PrintResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PrintResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PrintResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_StatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_StatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StatusRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ReturnMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ReturnMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReturnMessage_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
