// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: printer.proto

package grpc.examples.printer;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
