// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombooking.proto

package grpc.examples.roombooking;

public interface BookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>int64 date = 2;</code>
   */
  long getDate();

  /**
   * <code>int32 number = 3;</code>
   */
  int getNumber();

  /**
   * <code>int32 time = 4;</code>
   */
  int getTime();
}
