// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombooking.proto

package grpc.examples.roombooking;

public interface BookMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
