// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombooking.proto

package grpc.examples.roombooking;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();
}
