// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombooking.proto

package grpc.examples.roombooking;

public interface ReturnMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReturnMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
