// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombooking.proto

package grpc.examples.roombooking;

public interface RoomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *We will store the date as a long. Eg 20210427 = 2021-04-27 = 27 April 2020
   * </pre>
   *
   * <code>int64 date = 1;</code>
   */
  long getDate();
}
