// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombooking.proto

package grpc.examples.roombooking;

public final class RoombookingServiceImpl {
  private RoombookingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReturnMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReturnMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021roombooking.proto\"\033\n\013RoomRequest\022\014\n\004da" +
      "te\030\001 \001(\003\",\n\014RoomResponse\022\016\n\006number\030\001 \001(\005" +
      "\022\014\n\004time\030\002 \001(\005\"K\n\013BookRequest\022\020\n\010usernam" +
      "e\030\001 \001(\t\022\014\n\004date\030\002 \001(\003\022\016\n\006number\030\003 \001(\005\022\014\n" +
      "\004time\030\004 \001(\005\"*\n\013BookMessage\022\017\n\007message\030\001 " +
      "\001(\t\022\n\n\002id\030\002 \001(\005\"-\n\rDeleteRequest\022\020\n\010user" +
      "name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\" \n\rReturnMessage\022" +
      "\017\n\007message\030\001 \001(\t2\247\001\n\022RoombookingService\022" +
      "4\n\021getAvailableRooms\022\014.RoomRequest\032\r.Roo" +
      "mResponse\"\0000\001\022(\n\010bookRoom\022\014.BookRequest\032" +
      "\014.BookMessage\"\000\0221\n\rdeleteBooking\022\016.Delet" +
      "eRequest\032\016.ReturnMessage\"\000B5\n\031grpc.examp" +
      "les.roombookingB\026RoombookingServiceImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomRequest_descriptor,
        new java.lang.String[] { "Date", });
    internal_static_RoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomResponse_descriptor,
        new java.lang.String[] { "Number", "Time", });
    internal_static_BookRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookRequest_descriptor,
        new java.lang.String[] { "Username", "Date", "Number", "Time", });
    internal_static_BookMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BookMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookMessage_descriptor,
        new java.lang.String[] { "Message", "Id", });
    internal_static_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteRequest_descriptor,
        new java.lang.String[] { "Username", "Id", });
    internal_static_ReturnMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ReturnMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReturnMessage_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
