// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roombooking.proto

package grpc.examples.roombooking;

public interface RoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();

  /**
   * <code>int32 time = 2;</code>
   */
  int getTime();
}
